{% set name = "sbmlmath" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sbmlmath-{{ version }}.tar.gz
  sha256: 43f535a74e9d0a135173c35aa7fe3d9376d4d6d6fe292fb435a98f9d8a778b8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - python-libsbml >=5.20.4
    - sympy
    - pint
    - lxml >=4.6.4

test:
  imports:
    - sbmlmath
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dweindl/sbmlmath
  summary: SBML Math <-> SymPy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kaiserls
    - dweindl
